server:
    port: 8083
spring:
    application:
        name: catalogue-service
management.endpoints.web.exposure.include: hystrix.stream
eureka:
    client:
        serviceUrl:
            defaultZone: http://Eureka:8761/eureka/
        instance:
            preferIpAdress: true
            leaseRenewalIntervallInSeconds: 5
            metadataMap:
                instanceId: "${spring.application.name}:${random.value}"