server:
    port: 8082
spring:
    application:
        name: category-service

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        instance:
            preferIpAdress: true
            leaseRenewalIntervallInSeconds: 5
            metadataMap:
                instanceId: "${spring.application.name}:${random.value}"
