server:
  port: 8091
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: oauthclient

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 5
      metadataMap:
        instanceId: "${spring.application.name}:${random.value}"